[package]
name = "kea"
version = "0.1.0"
authors = ["Sam <sam.mackenzie@live.com>"]
edition = "2018"
license="MIT"
description="aur helper written in rust "
keywords = ["arch", "aur", "pacman", "arch", "yaourt"]

[dependencies]
alpm-rs="0.1.1"
aur-client="0.1.1"
clap = "2.32.0"